### ISSUE TITLE
Error occurred when executing DeepFuzeFaceSwap:  [WinError 267] The directory name is invalid

### ISSUE THREAD

**Issue by Nikolai1216** [SamKhoze/ComfyUI-DeepFuze#13]
Please help

Error occurred when executing DeepFuzeFaceSwap:

[WinError 267] The directory name is invalid

File "E:\Stability\Data\Packages\ComfyUI\execution.py", line 151, in recursive_execute
output_data, output_ui = get_output_data(obj, input_data_all)
File "E:\Stability\Data\Packages\ComfyUI\execution.py", line 81, in get_output_data
return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
File "E:\Stability\Data\Packages\ComfyUI\execution.py", line 74, in map_node_over_list
results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
File "E:\Stability\Data\Packages\ComfyUI\custom_nodes\ComfyUI-DeepFuze\nodes.py", line 959, in faceswampgenerate
result = subprocess.run(command,cwd="ComfyUI/custom_nodes/ComfyUI-DeepFuze",stdout=subprocess.PIPE)
File "subprocess.py", line 503, in run
File "subprocess.py", line 971, in __init__
File "subprocess.py", line 1456, in _execute_child

Close

**Comment by heiheiwodeo** [comment]
me too!!!

**Comment by heiheiwodeo** [comment]
Error occurred when executing DeepFuzeFaceSwap:

[WinError 267] The directory name is invalid

File "D:\ComfyUI-aki-v1.3\execution.py", line 152, in recursive_execute
output_data, output_ui = get_output_data(obj, input_data_all)
File "D:\ComfyUI-aki-v1.3\execution.py", line 82, in get_output_data
return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
File "D:\ComfyUI-aki-v1.3\execution.py", line 75, in map_node_over_list
results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
File "D:\ComfyUI-aki-v1.3\custom_nodes\ComfyUI-DeepFuze\nodes.py", line 959, in faceswampgenerate
result = subprocess.run(command,cwd="ComfyUI/custom_nodes/ComfyUI-DeepFuze",stdout=subprocess.PIPE)
File "D:\ComfyUI-aki-v1.3\python\lib\subprocess.py", line 503, in run
with Popen(*popenargs, **kwargs) as process:
File "", line 217, in sentry_patched_popen_init
File "D:\ComfyUI-aki-v1.3\python\lib\subprocess.py", line 971, in __init__
self._execute_child(args, executable, preexec_fn, close_fds,
File "D:\ComfyUI-aki-v1.3\python\lib\subprocess.py", line 1456, in _execute_child
hp, ht, pid, tid = _winapi.CreateProcess(executable, args,

**Comment by Nikolai1216** [comment]
Wow still no solution

**Comment by Steelman14aUA** [comment]
Same here

Prompt executor has been patched by Job Iterator!
1 1
video h265-mp4
{'enhancer': 'gpen_bfr_2048', 'faceswap_model': 'inswapper_128_fp16', 'frame_enhancer': 'ultra_sharp_x4', 'face_detector_model': 'retinaface', 'reference_face_index': 0, 'face_mask_padding_left': 0, 'face_mask_padding_right': 0, 'face_mask_padding_bottom': 0, 'face_mask_padding_top': 0, 'device': 'cuda', 'frame_rate': 25.0, 'loop_count': 0, 'filename_prefix': 'deepfuze', 'pingpong': False, 'save_output': True, 'source_images': ['25', 0], 'target_images': ['22', 0], 'format': 'video/h265-mp4', 'pix_fmt': 'yuv420p10le', 'crf': 22, 'save_metadata': ['save_metadata', 'BOOLEAN', {'default': True}]}   
E:\Ai\pinokio\api\comfyui.git\app\custom_nodes\ComfyUI-VideoHelperSuite\videohelpersuite\..\video_formats\h265-mp4.json
pix_fmt
crf
save_metadata
['python', './run.py', '--frame-processors', 'face_swapper', '-s', 'E:\\Ai\\pinokio\\api\\comfyui.git\\app\\output\\deepfuze_00004_.png', '-t', 'E:\\Ai\\pinokio\\api\\comfyui.git\\app\\output\\deepfuze_00004.mp4', '--face-detector-model', 'retinaface', '-o', 'E:\\Ai\\pinokio\\api\\comfyui.git\\app\\output\\deepfuze\\faceswap_17197397202485511.mp4', '--face-swapper-model', 'inswapper_128_fp16', '--reference-face-position', '0', '--face-mask-padding', '0', '0', '0', '0', '--headless', '--execution-providers', 'cuda']
!!! Exception during processing!!! [WinError 267] The directory name is invalid
Traceback (most recent call last):
  File "E:\Ai\pinokio\api\comfyui.git\app\execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "E:\Ai\pinokio\api\comfyui.git\app\execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "E:\Ai\pinokio\api\comfyui.git\app\execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "E:\Ai\pinokio\api\comfyui.git\app\custom_nodes\ComfyUI-DeepFuze-main\nodes.py", line 959, in faceswampgenerate
    result = subprocess.run(command,cwd="ComfyUI/custom_nodes/ComfyUI-DeepFuze",stdout=subprocess.PIPE)
  File "E:\Ai\pinokio\bin\miniconda\lib\subprocess.py", line 503, in run
    with Popen(*popenargs, **kwargs) as process:
  File "E:\Ai\pinokio\bin\miniconda\lib\subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "E:\Ai\pinokio\bin\miniconda\lib\subprocess.py", line 1456, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
NotADirectoryError: [WinError 267] The directory name is invalid

Prompt executed in 1.22 seconds

**Comment by piovis2023** [comment]
Do we have any solutions? I'm getting the same error

**Comment by Bortus-AI** [comment]
Having same issue and did install via comfui manager. Tried on 2 fresh installs of comfyui with both portable and nonportable versions.

**Comment by piovis2023** [comment]
@SamKhoze u/SamKhoze /SamKhoze

Can you please help?

We all really want to try your project. It looks really interesting.

**Comment by SamKhoze** [comment]
@Bortus-AI @piovis2023 I tested everything is working, perhaps is your installation, 
![IMG_9237](https://github.com/user-attachments/assets/6ca75323-bcac-4f00-ad4a-60e2f53fe860)

**Comment by piovis2023** [comment]
Thanks @SamKhoze 

Any ideas what we could do different?
Is it an issue with Windows 11 OS?

Did you reinstall yours from fresh?
If Comfy manager doesn't fix the nodes, whats the best way forwards? Could I send you my terminal response when I try to install?

Thanks

**Comment by Eikwang** [comment]
将NODES.PY中的path_cwd =改为完整路径.比如:path_cwd = os.path.abspath("D:\\ComfyUI\\custom_nodes\\ComfyUI-DeepFuze")
