### ISSUE TITLE
Error opening input: No such file or directory

### ISSUE THREAD

**Issue by rethink-studios** [SamKhoze/ComfyUI-DeepFuze#14]
Updated today, and received a new error.
Attaching workflow and video I used
(use whatever audio you like)

https://github.com/SamKhoze/ComfyUI-DeepFuze/assets/60104539/ebf783ed-a11f-4344-bd0d-48198e1b982b

[DEEPFUZE_06222024.json](https://github.com/user-attachments/files/15937945/DEEPFUZE_06222024.json)

BilboX LUTs path set to: D:\COMFYUI_BETA\ComfyUI\custom_nodes\bilbox-comfyui\luts
got prompt
'🔥 - 6 Nodes not included in prompt but is activated'
codeformer 25.0 video/h265-mp4
video h265-mp4
{'enhancer': 'codeformer', 'frame_enhancer': 'real_esrgan_x2', 'face_mask_padding_left': 0, 'face_mask_padding_right': 0, 'face_mask_padding_bottom': 0, 'face_mask_padding_top': 0, 'trim_frame_start': 0, 'trim_frame_end': 0, 'device': 'cpu', 'frame_rate': 25.0, 'loop_count': 0, 'filename_prefix': 'deepfuze', 'pingpong': False, 'save_output': True, 'images': ['1', 0], 'audio': ['11', 0], 'format': 'video/h265-mp4', 'pix_fmt': 'yuv420p10le', 'crf': 22, 'save_metadata': ['save_metadata', 'BOOLEAN', {'default': True}]}
D:\COMFYUI_BETA\ComfyUI\custom_nodes\ComfyUI-VideoHelperSuite\videohelpersuite\..\video_formats\h265-mp4.json
pix_fmt
crf
save_metadata
Output images were not of valid resolution and have had padding applied
D:\COMFYUI_BETA\ComfyUI\input\audio\17190807456734073.wav
['python', './run.py', '--frame-processors', 'lip_syncer', '-s', 'D:\\COMFYUI_BETA\\ComfyUI\\input\\audio\\17190807456734073.wav', '-t', 'D:\\COMFYUI_BETA\\ComfyUI\\output\\deepfuze_00001.mp4', '-o', 'D:\\COMFYUI_BETA\\ComfyUI\\output\\deepfuze\\17190807456830332.mp4', '--trim-frame-start', '0', '--trim-frame-end', '310', '--face-mask-padding', '0', '0', '0', '0', '--headless']
Traceback (most recent call last):
  File "D:\COMFYUI_BETA\ComfyUI\custom_nodes\ComfyUI-DeepFuze\run.py", line 7, in <module>
    from deepfuze import core
  File "D:\COMFYUI_BETA\ComfyUI\custom_nodes\ComfyUI-DeepFuze\.\deepfuze\core.py", line 16, in <module>
    from deepfuze.face_analyser import get_one_face, get_average_face
  File "D:\COMFYUI_BETA\ComfyUI\custom_nodes\ComfyUI-DeepFuze\.\deepfuze\face_analyser.py", line 10, in <module>
    from deepfuze.face_helper import estimate_matrix_by_face_landmark_5, warp_face_by_face_landmark_5, warp_face_by_translation, create_static_anchors, distance_to_face_landmark_5, distance_to_bounding_box, convert_face_landmark_68_to_5, apply_nms, categorize_age, categorize_gender
  File "D:\COMFYUI_BETA\ComfyUI\custom_nodes\ComfyUI-DeepFuze\.\deepfuze\face_helper.py", line 2, in <module>
    from cv2.typing import Size
ModuleNotFoundError: No module named 'cv2.typing'
['python', './run.py', '--frame-processors', 'face_enhancer', '--face-enhancer-model', 'codeformer', '-t', 'D:\\COMFYUI_BETA\\ComfyUI\\output\\deepfuze\\17190807456830332.mp4', '-o', 'D:\\COMFYUI_BETA\\ComfyUI\\output\\deepfuze\\enhanced_17190807456830332.mp4', '--headless']
Traceback (most recent call last):
  File "D:\COMFYUI_BETA\ComfyUI\custom_nodes\ComfyUI-DeepFuze\run.py", line 7, in <module>
    from deepfuze import core
  File "D:\COMFYUI_BETA\ComfyUI\custom_nodes\ComfyUI-DeepFuze\.\deepfuze\core.py", line 16, in <module>
    from deepfuze.face_analyser import get_one_face, get_average_face
  File "D:\COMFYUI_BETA\ComfyUI\custom_nodes\ComfyUI-DeepFuze\.\deepfuze\face_analyser.py", line 10, in <module>
    from deepfuze.face_helper import estimate_matrix_by_face_landmark_5, warp_face_by_face_landmark_5, warp_face_by_translation, create_static_anchors, distance_to_face_landmark_5, distance_to_bounding_box, convert_face_landmark_68_to_5, apply_nms, categorize_age, categorize_gender
  File "D:\COMFYUI_BETA\ComfyUI\custom_nodes\ComfyUI-DeepFuze\.\deepfuze\face_helper.py", line 2, in <module>
    from cv2.typing import Size
ModuleNotFoundError: No module named 'cv2.typing'
['python', './run.py', '--frame-processors', 'frame_enhancer', '--frame-enhancer-model', 'real_esrgan_x2', '-t', 'D:\\COMFYUI_BETA\\ComfyUI\\output\\deepfuze\\enhanced_17190807456830332.mp4', '-o', 'D:\\COMFYUI_BETA\\ComfyUI\\output\\deepfuze\\enhanced_17190807456830332.mp4', '--headless']
Traceback (most recent call last):
  File "D:\COMFYUI_BETA\ComfyUI\custom_nodes\ComfyUI-DeepFuze\run.py", line 7, in <module>
    from deepfuze import core
  File "D:\COMFYUI_BETA\ComfyUI\custom_nodes\ComfyUI-DeepFuze\.\deepfuze\core.py", line 16, in <module>
    from deepfuze.face_analyser import get_one_face, get_average_face
  File "D:\COMFYUI_BETA\ComfyUI\custom_nodes\ComfyUI-DeepFuze\.\deepfuze\face_analyser.py", line 10, in <module>
    from deepfuze.face_helper import estimate_matrix_by_face_landmark_5, warp_face_by_face_landmark_5, warp_face_by_translation, create_static_anchors, distance_to_face_landmark_5, distance_to_bounding_box, convert_face_landmark_68_to_5, apply_nms, categorize_age, categorize_gender
  File "D:\COMFYUI_BETA\ComfyUI\custom_nodes\ComfyUI-DeepFuze\.\deepfuze\face_helper.py", line 2, in <module>
    from cv2.typing import Size
ModuleNotFoundError: No module named 'cv2.typing'
ffmpeg version 2024-02-15-git-a2cfd6062c-essentials_build-www.gyan.dev Copyright (c) 2000-2024 the FFmpeg developers
  built with gcc 12.2.0 (Rev10, Built by MSYS2 project)
  configuration: --enable-gpl --enable-version3 --enable-static --pkg-config=pkgconf --disable-w32threads --disable-autodetect --enable-fontconfig --enable-iconv --enable-gnutls --enable-libxml2 --enable-gmp --enable-bzlib --enable-lzma --enable-zlib --enable-libsrt --enable-libssh --enable-libzmq --enable-avisynth --enable-sdl2 --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxvid --enable-libaom --enable-libopenjpeg --enable-libvpx --enable-mediafoundation --enable-libass --enable-libfreetype --enable-libfribidi --enable-libharfbuzz --enable-libvidstab --enable-libvmaf --enable-libzimg --enable-amf --enable-cuda-llvm --enable-cuvid --enable-ffnvcodec --enable-nvdec --enable-nvenc --enable-dxva2 --enable-d3d11va --enable-libvpl --enable-libgme --enable-libopenmpt --enable-libopencore-amrwb --enable-libmp3lame --enable-libtheora --enable-libvo-amrwbenc --enable-libgsm --enable-libopencore-amrnb --enable-libopus --enable-libspeex --enable-libvorbis --enable-librubberband
  libavutil      58. 38.100 / 58. 38.100
  libavcodec     60. 39.100 / 60. 39.100
  libavformat    60. 21.100 / 60. 21.100
  libavdevice    60.  4.100 / 60.  4.100
  libavfilter     9. 17.100 /  9. 17.100
  libswscale      7.  6.100 /  7.  6.100
  libswresample   4. 13.100 /  4. 13.100
  libpostproc    57.  4.100 / 57.  4.100
[in#0 @ 0000013a1ab00540] Error opening input: No such file or directory
Error opening input file D:\COMFYUI_BETA\ComfyUI\output\deepfuze\enhanced_17190807456830332.mp4.
Error opening input files: No such file or directory
None
None
!!! Exception during processing!!! D:\COMFYUI_BETA\ComfyUI\output\deepfuze\enhanced_17190807456830332_.mp4 could not be loaded with cv.
Traceback (most recent call last):
  File "D:\COMFYUI_BETA\ComfyUI\execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\COMFYUI_BETA\ComfyUI\execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\COMFYUI_BETA\ComfyUI\execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\COMFYUI_BETA\ComfyUI\custom_nodes\ComfyUI-DeepFuze\nodes.py", line 1425, in lipsyncgenerate
    return load_video_cv(filename,0,'Disabled',512,512,0,0,1)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\COMFYUI_BETA\ComfyUI\custom_nodes\ComfyUI-DeepFuze\nodes.py", line 543, in load_video_cv
    (width, height, fps, duration, total_frames, target_frame_time) = next(gen)
                                                                      ^^^^^^^^^
  File "D:\COMFYUI_BETA\ComfyUI\custom_nodes\ComfyUI-DeepFuze\nodes.py", line 462, in cv_frame_generator
    raise ValueError(f"{video} could not be loaded with cv.")
ValueError: D:\COMFYUI_BETA\ComfyUI\output\deepfuze\enhanced_17190807456830332_.mp4 could not be loaded with cv.

Prompt executed in 6.48 seconds

**Comment by von-fss** [comment]
Same error here.

What i tried ?
- I reinstall comfyui with deepfuze follow all the steps 3 times.
- I read all the issues open and tried to fix.
- Verified every package version.
- CUDA installed version and CDnn match.
- The issue appear both CUDA and CPU run.
- Tried the frame cap as mentioned on #15 but no sucess

Packages:
onnxruntime-gpu version
![image](https://github.com/user-attachments/assets/098ac057-ffec-4725-8dad-a57985251bc7)
The version 1.18.1 not work as mentioned on another issue comment.

CUDA
![image](https://github.com/user-attachments/assets/3ef155dc-a73b-443f-acca-e6c8617ead43)

opencv and headless up to date
![image](https://github.com/user-attachments/assets/ba48e87e-86a3-48df-8ad0-7cc2189b27c7)

The error msg:
![image](https://github.com/user-attachments/assets/e3978453-4aff-4a44-bc48-ee593514a8cf)

Thats the workflow for reference:
![image](https://github.com/user-attachments/assets/5392aa94-9ef9-4c09-956d-c60d26d27a08)

Thanks a lot! Your work is amazing !
