### ISSUE TITLE
[ERROR] An error occurred while retrieving information for the 'DeepFuzeAdavance' node. 'DeepFuzeFaceSwap' node.

### ISSUE THREAD

**Issue by DtiSignal** [SamKhoze/ComfyUI-DeepFuze#23]
Hello every one. Help please!! 

FETCH DATA from: E:\GitHub_projects\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager\extension-node-map.json [DONE]
[ERROR] An error occurred while retrieving information for the 'DeepFuzeAdavance' node.
Traceback (most recent call last):
  File "E:\GitHub_projects\ComfyUI_windows_portable\ComfyUI\server.py", line 415, in get_object_info
    out[x] = node_info(x)
             ^^^^^^^^^^^^
  File "E:\GitHub_projects\ComfyUI_windows_portable\ComfyUI\server.py", line 393, in node_info
    info['input'] = obj_class.INPUT_TYPES()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\GitHub_projects\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-DeepFuze\nodes.py", line 1033, in INPUT_TYPES
    ffmpeg_formats = get_video_formats()
                     ^^^^^^^^^^^^^^^^^^^
  File "E:\GitHub_projects\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-DeepFuze\nodes.py", line 268, in get_video_formats
    for format_name in folder_paths.get_filename_list("VHS_video_formats"):
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\GitHub_projects\ComfyUI_windows_portable\ComfyUI\folder_paths.py", line 225, in get_filename_list
    out = get_filename_list_(folder_name)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\GitHub_projects\ComfyUI_windows_portable\ComfyUI\folder_paths.py", line 192, in get_filename_list_
    folders = folder_names_and_paths[folder_name]
              ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
KeyError: 'VHS_video_formats'

[ERROR] An error occurred while retrieving information for the 'DeepFuzeFaceSwap' node.
Traceback (most recent call last):
  File "E:\GitHub_projects\ComfyUI_windows_portable\ComfyUI\server.py", line 415, in get_object_info
    out[x] = node_info(x)
             ^^^^^^^^^^^^
  File "E:\GitHub_projects\ComfyUI_windows_portable\ComfyUI\server.py", line 393, in node_info
    info['input'] = obj_class.INPUT_TYPES()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\GitHub_projects\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-DeepFuze\nodes.py", line 610, in INPUT_TYPES
    ffmpeg_formats = get_video_formats()
                     ^^^^^^^^^^^^^^^^^^^
  File "E:\GitHub_projects\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-DeepFuze\nodes.py", line 268, in get_video_formats
    for format_name in folder_paths.get_filename_list("VHS_video_formats"):
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\GitHub_projects\ComfyUI_windows_portable\ComfyUI\folder_paths.py", line 225, in get_filename_list
    out = get_filename_list_(folder_name)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\GitHub_projects\ComfyUI_windows_portable\ComfyUI\folder_paths.py", line 192, in get_filename_list_
    folders = folder_names_and_paths[folder_name]
              ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
KeyError: 'VHS_video_formats'

**Comment by BIGDAVE-223** [comment]
I am also encountering this exact same error

EDIT: my apologies i didn't read enough of the readme Ill leave the solution here though

You need to install this node as well and it will load up just fine  https://github.com/Kosinkadink/ComfyUI-VideoHelperSuite
