### ISSUE TITLE
node not working

### ISSUE THREAD

**Issue by raochinmay6** [SamKhoze/ComfyUI-DeepFuze#26]
![Screenshot (28)](https://github.com/SamKhoze/ComfyUI-DeepFuze/assets/160831464/b63caf07-870e-4678-bcac-391a9e9a7479)
[comfyui.log](https://github.com/user-attachments/files/16157506/comfyui.log)

**Comment by raochinmay6** [comment]
!!! Exception during processing!!! 'dict' object is not callable
Traceback (most recent call last):
  File "E:\ComfyUI_windows_portable\ComfyUI\execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ComfyUI_windows_portable\ComfyUI\execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ComfyUI_windows_portable\ComfyUI\execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-DeepFuze\nodes.py", line 1339, in lipsyncgenerate
    open(audio_file,"wb").write(audio())
                                ^^^^^^^
TypeError: 'dict' object is not callable

Prompt executed in 2.10 seconds
got prompt
Failed to validate prompt for output 49:
* (prompt):
  - Required input is missing: audio
* PlayBackAudio 49:
  - Required input is missing: audio
Output will be ignored
[rgthree] Using rgthree's optimized recursive execution.
codeformer 24.0 video/h265-mp4
video h265-mp4
{'enhancer': 'codeformer', 'frame_enhancer': 'clear_reality_x4', 'face_mask_padding_left': 0, 'face_mask_padding_right': 0, 'face_mask_padding_bottom': 0, 'face_mask_padding_top': 0, 'trim_frame_start': 0, 'trim_frame_end': 0, 'device': 'cpu', 'frame_rate': 24.0, 'loop_count': 0, 'filename_prefix': 'deepfuze', 'pingpong': False, 'save_output': True, 'images': ['35', 0], 'audio': ['41', 0], 'format': 'video/h265-mp4', 'pix_fmt': 'yuv420p10le', 'crf': 22, 'save_metadata': ['save_metadata', 'BOOLEAN', {'default': True}]}
E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-VideoHelperSuite\videohelpersuite\..\video_formats\h265-mp4.json
pix_fmt
crf
save_metadata
!!! Exception during processing!!! 'dict' object is not callable
Traceback (most recent call last):
  File "E:\ComfyUI_windows_portable\ComfyUI\execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ComfyUI_windows_portable\ComfyUI\execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ComfyUI_windows_portable\ComfyUI\execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-DeepFuze\nodes.py", line 1339, in lipsyncgenerate
    open(audio_file,"wb").write(audio())
                                ^^^^^^^
TypeError: 'dict' object is not callable

Prompt executed in 1.22 seconds
got prompt
Failed to validate prompt for output 45:
* VAEEncodeAudio 59:
  - Required input is missing: vae
* VAEDecode 60:
  - Required input is missing: vae
Output will be ignored
Failed to validate prompt for output 49:
* (prompt):
  - Required input is missing: audio
* PlayBackAudio 49:
  - Required input is missing: audio
Output will be ignored
Failed to validate prompt for output 52:
* DeepFuzeAdavance 57:
  - Required input is missing: audio
Output will be ignored
[rgthree] Using rgthree's optimized recursive execution.
!!! Exception during processing!!! DeepFuzeAdavance.lipsyncgenerate() missing 1 required positional argument: 'audio'
Traceback (most recent call last):
  File "E:\ComfyUI_windows_portable\ComfyUI\execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ComfyUI_windows_portable\ComfyUI\execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ComfyUI_windows_portable\ComfyUI\execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: DeepFuzeAdavance.lipsyncgenerate() missing 1 required positional argument: 'audio'

Prompt executed in 0.02 seconds
got prompt
Failed to validate prompt for output 49:
* (prompt):
  - Required input is missing: audio
* PlayBackAudio 49:
  - Required input is missing: audio
Output will be ignored
[rgthree] Using rgthree's optimized recursive execution.
None 25.0 video/h265-mp4
video h265-mp4
{'enhancer': 'None', 'frame_enhancer': 'None', 'face_mask_padding_left': 0, 'face_mask_padding_right': 0, 'face_mask_padding_bottom': 0, 'face_mask_padding_top': 0, 'trim_frame_start': 0, 'trim_frame_end': 0, 'device': 'cpu', 'frame_rate': 25.0, 'loop_count': 0, 'filename_prefix': 'deepfuze', 'pingpong': False, 'save_output': True, 'images': ['35', 0], 'audio': ['41', 0], 'format': 'video/h265-mp4', 'pix_fmt': 'yuv420p10le', 'crf': 22, 'save_metadata': ['save_metadata', 'BOOLEAN', {'default': True}]}
E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-VideoHelperSuite\videohelpersuite\..\video_formats\h265-mp4.json
pix_fmt
crf
save_metadata
!!! Exception during processing!!! 'dict' object is not callable
Traceback (most recent call last):
  File "E:\ComfyUI_windows_portable\ComfyUI\execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ComfyUI_windows_portable\ComfyUI\execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ComfyUI_windows_portable\ComfyUI\execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-DeepFuze\nodes.py", line 1339, in lipsyncgenerate
    open(audio_file,"wb").write(audio())
                                ^^^^^^^
TypeError: 'dict' object is not callable

Prompt executed in 1.21 seconds
got prompt
Failed to validate prompt for output 49:
* (prompt):
  - Required input is missing: audio
* PlayBackAudio 49:
  - Required input is missing: audio
Output will be ignored
[rgthree] Using rgthree's optimized recursive execution.
None 25.0 video/h265-mp4
video h265-mp4
{'enhancer': 'None', 'frame_enhancer': 'None', 'face_mask_padding_left': 0, 'face_mask_padding_right': 0, 'face_mask_padding_bottom': 0, 'face_mask_padding_top': 0, 'trim_frame_start': 0, 'trim_frame_end': 0, 'device': 'cpu', 'frame_rate': 25.0, 'loop_count': 0, 'filename_prefix': 'deepfuze', 'pingpong': False, 'save_output': True, 'images': ['35', 0], 'audio': ['41', 0], 'format': 'video/h265-mp4', 'pix_fmt': 'yuv420p10le', 'crf': 22, 'save_metadata': ['save_metadata', 'BOOLEAN', {'default': True}]}
E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-VideoHelperSuite\videohelpersuite\..\video_formats\h265-mp4.json
pix_fmt
crf
save_metadata
!!! Exception during processing!!! 'dict' object is not callable
Traceback (most recent call last):
  File "E:\ComfyUI_windows_portable\ComfyUI\execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ComfyUI_windows_portable\ComfyUI\execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ComfyUI_windows_portable\ComfyUI\execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-DeepFuze\nodes.py", line 1339, in lipsyncgenerate
    open(audio_file,"wb").write(audio())
                                ^^^^^^^
TypeError: 'dict' object is not callable

Prompt executed in 1.25 seconds

**Comment by raochinmay6** [comment]
somehow my node is working but lip sync is not visible, I mean I barely see lip moving... what to do ?

**Comment by manniee07** [comment]
I think it bugs out when it loses track of the facial movements.
