### ISSUE TITLE
Issue with main nodes, MP4 cannot be loaded with cv, Nonetype object has no attribute encode

### ISSUE THREAD

**Issue by DarkVamprism** [SamKhoze/ComfyUI-DeepFuze#41]
Each node has a different error, the TTS node gives me
`stdout: b' > Using model: xtts\r\n > Text splitted to sentences.\r\n[\'This is a test\']\r\nTraceback (most recent call last):\r\n  File "C:\\Software\\AIPrograms\\StabilityMatrix\\Data\\Packages\\ComfyUI\\custom_nodes\\ComfyUI-DeepFuze\\tts_generation.py", line 36, in <module>\r\n    main()\r\n  File "C:\\Software\\AIPrograms\\StabilityMatrix\\Data\\Packages\\ComfyUI\\custom_nodes\\ComfyUI-DeepFuze\\tts_generation.py", line 33, in main\r\n    tts.tts_to_file(text=args.text, speaker_wav=args.speaker_wav, language=args.language, file_path=args.output_file)\r\n  File "C:\\Software\\AIPrograms\\StabilityMatrix\\Data\\Packages\\ComfyUI\\custom_nodes\\ComfyUI-DeepFuze\\TTS\\api.py", line 334, in tts_to_file\r\n    wav = self.tts(\r\n  File "C:\\Software\\AIPrograms\\StabilityMatrix\\Data\\Packages\\ComfyUI\\custom_nodes\\ComfyUI-DeepFuze\\TTS\\api.py", line 276, in tts\r\n    wav = self.synthesizer.tts(\r\n  File "C:\\Software\\AIPrograms\\StabilityMatrix\\Data\\Packages\\ComfyUI\\custom_nodes\\ComfyUI-DeepFuze\\TTS\\utils\\synthesizer.py", line 386, in tts\r\n    outputs = self.tts_model.synthesize(\r\n  File "C:\\Software\\AIPrograms\\StabilityMatrix\\Data\\Packages\\ComfyUI\\custom_nodes\\ComfyUI-DeepFuze\\TTS\\tts\\models\\xtts.py", line 419, in synthesize\r\n    return self.full_inference(text, speaker_wav, language, **settings)\r\n  File "C:\\Software\\AIPrograms\\StabilityMatrix\\Data\\Packages\\ComfyUI\\venv\\lib\\site-packages\\torch\\utils\\_contextlib.py", line 115, in decorate_context\r\n    return func(*args, **kwargs)\r\n  File "C:\\Software\\AIPrograms\\StabilityMatrix\\Data\\Packages\\ComfyUI\\custom_nodes\\ComfyUI-DeepFuze\\TTS\\tts\\models\\xtts.py", line 488, in full_inference\r\n    return self.inference(\r\n  File "C:\\Software\\AIPrograms\\StabilityMatrix\\Data\\Packages\\ComfyUI\\venv\\lib\\site-packages\\torch\\utils\\_contextlib.py", line 115, in decorate_context\r\n    return func(*args, **kwargs)\r\n  File "C:\\Software\\AIPrograms\\StabilityMatrix\\Data\\Packages\\ComfyUI\\custom_nodes\\ComfyUI-DeepFuze\\TTS\\tts\\models\\xtts.py", line 534, in inference\r\n    text_tokens = torch.IntTensor(self.tokenizer.encode(sent, lang=language)).unsqueeze(0).to(self.device)\r\n  File "C:\\Software\\AIPrograms\\StabilityMatrix\\Data\\Packages\\ComfyUI\\custom_nodes\\ComfyUI-DeepFuze\\TTS\\tts\\layers\\xtts\\tokenizer.py", line 653, in encode\r\n    return self.tokenizer.encode(txt).ids\r\nAttributeError: \'NoneType\' object has no attribute \'encode\'\r\n'`

Lipsync and Faceswap both gives
`C:\Software\AIPrograms\StabilityMatrix\Data\Packages\ComfyUI\output\deepfuze\17232748969994147.mp4 could not be loaded with cv.`

**Comment by ItsmeEsal** [comment]
In my case, i have reinstalling onnxruntime-gpu to spesific version, not new version. try install onnxruntime-gpu version 1.18.0, in my case this version work fine. maybe this node not supported new version of onnxruntime-gpu
