### ISSUE TITLE
No module named 'cv2'

### ISSUE THREAD

**Issue by WhiteTr4sh** [SamKhoze/ComfyUI-DeepFuze#43]
When I restart CompfyUI I get the following output.

C:\AI\ComfyUI_windows_portable>.\python_embeded\python.exe -s ComfyUI\main.py --windows-standalone-build
Total VRAM 6144 MB, total RAM 15724 MB
pytorch version: 2.3.1+cu121
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 3060 Laptop GPU : cudaMallocAsync
Using pytorch cross attention
[Prompt Server] web root: C:\AI\ComfyUI_windows_portable\ComfyUI\web
Traceback (most recent call last):
  File "C:\AI\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1941, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-DeepFuze\__init__.py", line 1, in <module>
    from .nodes import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
  File "C:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-DeepFuze\nodes.py", line 7, in <module>
    import cv2
ModuleNotFoundError: No module named 'cv2'

Cannot import C:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-DeepFuze module for custom nodes: No module named 'cv2'

Import times for custom nodes:
   0.0 seconds: C:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\websocket_image_save.py
   0.0 seconds (IMPORT FAILED): C:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-DeepFuze

Starting server

To see the GUI go to: http://127.0.0.1:8188

**Comment by vnyash** [comment]
Hello @WhiteTr4sh,
Node is not correctly installed that's why you are facing this issue
