### ISSUE TITLE
Error occurred when executing DeepFuzeFaceSwap

### ISSUE THREAD

**Issue by Zakutu** [SamKhoze/ComfyUI-DeepFuze#5]
Error occurred when executing DeepFuzeFaceSwap:

C:\ComfyUI_windows_portable\ComfyUI\output\deepfuze\faceswap_17187334906389506.mp4 could not be loaded with cv.

File "C:\ComfyUI_windows_portable\ComfyUI\execution.py", line 151, in recursive_execute
output_data, output_ui = get_output_data(obj, input_data_all)
File "C:\ComfyUI_windows_portable\ComfyUI\execution.py", line 81, in get_output_data
return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
File "C:\ComfyUI_windows_portable\ComfyUI\execution.py", line 74, in map_node_over_list
results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
File "C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-DeepFuze\nodes.py", line 1018, in faceswampgenerate
return load_video_cv(faceswap_filename,0,'Disabled',512,512,0,0,1)
File "C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-DeepFuze\nodes.py", line 543, in load_video_cv
(width, height, fps, duration, total_frames, target_frame_time) = next(gen)
File "C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-DeepFuze\nodes.py", line 462, in cv_frame_generator
raise ValueError(f"{video} could not be loaded with cv.")

**Comment by SamKhoze** [comment]
What node are you using for loading audio and what audio format are you uploading? Please review the requirements for the audio loader and try using an mp3 file as other file types may cause errors. We are also working on developing a converter node to convert audio to a unified format.

**Comment by iordcalin** [comment]
Same problem for me as well.I'm using the official workflow and your own video /image assets

**Comment by SamKhoze** [comment]
@iordcalin The error message suggests most likely due to your installation. Make sure OpenCV is installed, go to your comfyui manager use the pip install tool type opencv-python , and click ok. I recommend deleting your DeepFuze folder and following the installation instructions for Windows or Mac. Additional steps are required to make this work because of the nature of Lipsync Generation and Voice Cloning. If the error remains the same please let us know.

**Comment by SamKhoze** [comment]
@iordcalin & @Zakutu you will get the cv load error If you have selected MPS or CUDA in your device options, please note that MPS is for MAC and CUDA will be released later. For now, you can use it on CPU, which will take a longer time if you apply face enhancer and frame enhancers."

**Comment by iordcalin** [comment]
@SamKhoze CPU is selected in the DeepFuze FaceSwap,is there another way to set the device options?
I installed opencv and still getting this error...

**Comment by FLYleoYBQ** [comment]
same question，When the opencv installation is complete, a message indicating that cv cannot be loaded is displayed

**Comment by Rex-Liu1027** [comment]
> same question，When the opencv installation is complete, a message indicating that cv cannot be loaded is display

Hi,is it compatibled with Linux？thx~

**Comment by SamKhoze** [comment]
@Rex-Liu1027 Yes, follow the Mac installation via conda env. Once it's installed, I would appreciate it if you could document it and share with me. I can add it to the README.md. It will work with CPU, still I'm trying to find a way how to enable CUDA installation, the code is written for CUDA.

**Comment by Bortus-AI** [comment]
I'm on windows and having the same error using CPU. I get the CV error like the others. opencv-python is already installed

**Comment by SamKhoze** [comment]
@Bortus-AI Upgrade your opencv check the error section on the readme file

**Comment by Bortus-AI** [comment]
@SamKhoze already upgraded opencv and followed the error section. I tried on a fresh install of comfui as well and same issue

**Comment by Bortus-AI** [comment]
@SamKhoze redownloaded comfyui again but using different python version and pytorch and used the comfyui manager to install deepfuze but I get the following error

[WinError 267] The directory name is invalid

```
#######################################################################
[ComfyUI-Manager] Starting dependency installation/(de)activation for the extension


## ComfyUI-Manager: EXECUTE => ['C:\\Users\\bpvar\\AppData\\Local\\Programs\\Python\\Python311\\python.exe', '-m', 'pip', 'install', 'imageio_ffmpeg']

## Execute install/(de)activation script for 'C:\Users\bpvar\OneDrive\Desktop\ComfyUI\custom_nodes\ComfyUI-DeepFuze'

## ComfyUI-Manager: EXECUTE => ['C:\\Users\\bpvar\\AppData\\Local\\Programs\\Python\\Python311\\python.exe', '-m', 'pip', 'install', 'cython>=0.29.30']

## Execute install/(de)activation script for 'C:\Users\bpvar\OneDrive\Desktop\ComfyUI\custom_nodes\ComfyUI-DeepFuze'
 [ERROR] Failed to execute install/(de)activation script: ['C:\\Users\\bpvar\\OneDrive\\Desktop\\ComfyUI\\custom_nodes\\ComfyUI-DeepFuze', 'C:\\Users\\bpvar\\AppData\\Local\\Programs\\Python\\Python311\\python.exe', '-m', 'pip', 'install', 'torch>=2.1']
 / invalid version number '2.3.0+cu118'
[SKIP] Downgrading pip package isn't allowed: soundfile (cur=0.12.1)
[SKIP] Downgrading pip package isn't allowed: scikit-learn (cur=1.5.1)
[SKIP] Downgrading pip package isn't allowed: numba (cur=0.60.0)
[SKIP] Downgrading pip package isn't allowed: inflect (cur=7.3.1)
[SKIP] Downgrading pip package isn't allowed: tqdm (cur=4.66.4)
[SKIP] Downgrading pip package isn't allowed: anyascii (cur=0.3.2)

## ComfyUI-Manager: EXECUTE => ['C:\\Users\\bpvar\\AppData\\Local\\Programs\\Python\\Python311\\python.exe', '-m', 'pip', 'install', 'pyyaml>=6.0']

## Execute install/(de)activation script for 'C:\Users\bpvar\OneDrive\Desktop\ComfyUI\custom_nodes\ComfyUI-DeepFuze'
 [ERROR] Failed to execute install/(de)activation script: ['C:\\Users\\bpvar\\OneDrive\\Desktop\\ComfyUI\\custom_nodes\\ComfyUI-DeepFuze', 'C:\\Users\\bpvar\\AppData\\Local\\Programs\\Python\\Python311\\python.exe', '-m', 'pip', 'install', 'fsspec>=2023.6.0 # <= 2023.9.1 makes aux tests fail']
 / invalid version number '2023.6.0 # <= 2023.9.1 makes aux tests fail'
[SKIP] Downgrading pip package isn't allowed: aiohttp (cur=3.9.5)
[SKIP] Downgrading pip package isn't allowed: packaging (cur=24.1)

## ComfyUI-Manager: EXECUTE => ['C:\\Users\\bpvar\\AppData\\Local\\Programs\\Python\\Python311\\python.exe', '-m', 'pip', 'install', 'flask>=2.0.1']

## Execute install/(de)activation script for 'C:\Users\bpvar\OneDrive\Desktop\ComfyUI\custom_nodes\ComfyUI-DeepFuze'
        [SKIP] Downgrading pip package isn't allowed: umap-learn (cur=0.5.6)
[ERROR] Failed to execute install/(de)activation script: ['C:\\Users\\bpvar\\OneDrive\\Desktop\\ComfyUI\\custom_nodes\\ComfyUI-DeepFuze', 'C:\\Users\\bpvar\\AppData\\Local\\Programs\\Python\\Python311\\python.exe', '-m', 'pip', 'install', 'pandas>=1.4,<2.0']
 / invalid version number '1.4,<2.0'
[SKIP] Downgrading pip package isn't allowed: matplotlib (cur=3.9.1)
[SKIP] Downgrading pip package isn't allowed: coqpit (cur=0.0.17)

## ComfyUI-Manager: EXECUTE => ['C:\\Users\\bpvar\\AppData\\Local\\Programs\\Python\\Python311\\python.exe', '-m', 'pip', 'install', 'hangul_romanize']

## Execute install/(de)activation script for 'C:\Users\bpvar\OneDrive\Desktop\ComfyUI\custom_nodes\ComfyUI-DeepFuze'

## ComfyUI-Manager: EXECUTE => ['C:\\Users\\bpvar\\AppData\\Local\\Programs\\Python\\Python311\\python.exe', '-m', 'pip', 'install', 'gruut[de,es,fr]==2.2.3']

## Execute install/(de)activation script for 'C:\Users\bpvar\OneDrive\Desktop\ComfyUI\custom_nodes\ComfyUI-DeepFuze'
                    [SKIP] Downgrading pip package isn't allowed: g2pkk (cur=0.1.2)
[SKIP] Downgrading pip package isn't allowed: einops (cur=0.8.0)
[SKIP] Downgrading pip package isn't allowed: transformers (cur=4.42.3)

## ComfyUI-Manager: EXECUTE => ['C:\\Users\\bpvar\\AppData\\Local\\Programs\\Python\\Python311\\python.exe', '-m', 'pip', 'install', 'unidecode>=1.3.2']

## Execute install/(de)activation script for 'C:\Users\bpvar\OneDrive\Desktop\ComfyUI\custom_nodes\ComfyUI-DeepFuze'

## ComfyUI-Manager: EXECUTE => ['C:\\Users\\bpvar\\AppData\\Local\\Programs\\Python\\Python311\\python.exe', '-m', 'pip', 'install', 'spacy[ja]>=3']

## Execute install/(de)activation script for 'C:\Users\bpvar\OneDrive\Desktop\ComfyUI\custom_nodes\ComfyUI-DeepFuze'

## ComfyUI-Manager: EXECUTE => ['C:\\Users\\bpvar\\AppData\\Local\\Programs\\Python\\Python311\\python.exe', 'install.py']

## Execute install/(de)activation script for 'C:\Users\bpvar\OneDrive\Desktop\ComfyUI\custom_nodes\ComfyUI-DeepFuze'
 Conda is not activated

install/(de)activation script failed: C:\Users\bpvar\OneDrive\Desktop\ComfyUI\custom_nodes\ComfyUI-DeepFuze

[ComfyUI-Manager] Startup script completed.
#######################################################################
```

```
To see the GUI go to: http://127.0.0.1:8188
got prompt
1 6
video h265-mp4
{'enhancer': 'codeformer', 'faceswap_model': 'inswapper_128_fp16', 'frame_enhancer': 'clear_reality_x4', 'face_detector_model': 'retinaface', 'reference_face_index': 0, 'face_mask_padding_left': 0, 'face_mask_padding_right': 0, 'face_mask_padding_bottom': 0, 'face_mask_padding_top': 0, 'device': 'cuda', 'frame_rate': 25.0, 'loop_count': 0, 'filename_prefix': 'deepfuze', 'pingpong': False, 'save_output': True, 'source_images': ['10', 0], 'target_images': ['11', 0], 'format': 'video/h265-mp4', 'pix_fmt': 'yuv420p10le', 'crf': 22, 'save_metadata': ['save_metadata', 'BOOLEAN', {'default': True}]}
C:\Users\bpvar\OneDrive\Desktop\ComfyUI\custom_nodes\ComfyUI-VideoHelperSuite\videohelpersuite\..\video_formats\h265-mp4.json
pix_fmt
crf
save_metadata
Output images were not of valid resolution and have had padding applied
['python', './run.py', '--frame-processors', 'face_swapper', '-s', 'C:\\Users\\bpvar\\OneDrive\\Desktop\\ComfyUI\\output\\deepfuze_00004_.png', '-t', 'C:\\Users\\bpvar\\OneDrive\\Desktop\\ComfyUI\\output\\deepfuze_00004.mp4', '--face-detector-model', 'retinaface', '-o', 'C:\\Users\\bpvar\\OneDrive\\Desktop\\ComfyUI\\output\\deepfuze\\faceswap_17214119937331405.mp4', '--face-swapper-model', 'inswapper_128_fp16', '--reference-face-position', '0', '--face-mask-padding', '0', '0', '0', '0', '--headless', '--execution-providers', 'cuda']
!!! Exception during processing!!! [WinError 267] The directory name is invalid
Traceback (most recent call last):
  File "C:\Users\bpvar\OneDrive\Desktop\ComfyUI\execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bpvar\OneDrive\Desktop\ComfyUI\execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bpvar\OneDrive\Desktop\ComfyUI\execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bpvar\OneDrive\Desktop\ComfyUI\custom_nodes\ComfyUI-DeepFuze\nodes.py", line 864, in faceswampgenerate
    result = subprocess.run(command,cwd="ComfyUI/custom_nodes/ComfyUI-DeepFuze",stdout=subprocess.PIPE)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bpvar\AppData\Local\Programs\Python\Python311\Lib\subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bpvar\AppData\Local\Programs\Python\Python311\Lib\subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\bpvar\AppData\Local\Programs\Python\Python311\Lib\subprocess.py", line 1538, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
NotADirectoryError: [WinError 267] The directory name is invalid
```

**Comment by Bortus-AI** [comment]
happens with cpu or cuda

**Comment by Bortus-AI** [comment]
> @SamKhoze already upgraded opencv and followed the error section. I tried on a fresh install of comfui as well and same issue

Anything I can try to fix this? Already downloaded your new commit from yesterday but no change

**Comment by Bortus-AI** [comment]
@SamKhoze interesting enough if I set the frame load cap to a specific number I get no errors with cpu or cuda.

**Comment by Bortus-AI** [comment]
> Reference in new issue



> @SamKhoze interesting enough if I set the frame load cap to a specific number I get no errors with cpu or cuda.

Its a bit hit and miss. Worked for one video but now the next 3 videos have the CV error again
