### ISSUE TITLE
mp4 could not be loaded with cv 

### ISSUE THREAD

**Issue by klaatuka** [SamKhoze/ComfyUI-DeepFuze#54]
please help me solve the error

C:\AI\ComfyUI_windows_portable\ComfyUI\output\deepfuze\faceswap_17299500601466925.mp4 could not be loaded with cv.

File "C:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-DeepFuze\nodes.py", line 365, in cv_frame_generator
    raise ValueError(f"{video} could not be loaded with cv.")
ValueError: C:\AI\ComfyUI_windows_portable\ComfyUI\output\deepfuze\faceswap_1729949595164198.mp4 could not be loaded with cv.

Prompt executed in 3.19 seconds

and this:

# ComfyUI Error Report
## Error Details
- **Node Type:** DeepFuzeFaceSwap
- **Exception Type:** ValueError
- **Exception Message:** C:\AI\ComfyUI_windows_portable\ComfyUI\output\deepfuze\faceswap_17299500601466925.mp4 could not be loaded with cv.
## Stack Trace
```
  File "C:\AI\ComfyUI_windows_portable\ComfyUI\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "C:\AI\ComfyUI_windows_portable\ComfyUI\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "C:\AI\ComfyUI_windows_portable\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)

  File "C:\AI\ComfyUI_windows_portable\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "C:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-DeepFuze\nodes.py", line 928, in faceswampgenerate
    return load_video_cv(faceswap_filename,0,'Disabled',512,512,0,0,1)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "C:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-DeepFuze\nodes.py", line 446, in load_video_cv
    (width, height, fps, duration, total_frames, target_frame_time) = next(gen)
                                                                      ^^^^^^^^^

  File "C:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-DeepFuze\nodes.py", line 365, in cv_frame_generator
    raise ValueError(f"{video} could not be loaded with cv.")

```
## System Information
- **ComfyUI Version:** v0.2.4-9-gc3ffbae
- **Arguments:** ComfyUI\main.py --windows-standalone-build
- **OS:** nt
- **Python Version:** 3.12.7 (tags/v3.12.7:0b05ead, Oct  1 2024, 03:06:41) [MSC v.1941 64 bit (AMD64)]
- **Embedded Python:** true
- **PyTorch Version:** 2.5.0+cu124
## Devices

- **Name:** cuda:0 NVIDIA GeForce RTX 4060 Ti : cudaMallocAsync
  - **Type:** cuda
  - **VRAM Total:** 17175150592
  - **VRAM Free:** 15964569600
  - **Torch VRAM Total:** 0
  - **Torch VRAM Free:** 0

## Logs
```
2024-10-26 16:20:41,269 - root - INFO - Total VRAM 16380 MB, total RAM 65375 MB
2024-10-26 16:20:41,269 - root - INFO - pytorch version: 2.5.0+cu124
2024-10-26 16:20:41,270 - root - INFO - Set vram state to: NORMAL_VRAM
2024-10-26 16:20:41,270 - root - INFO - Device: cuda:0 NVIDIA GeForce RTX 4060 Ti : cudaMallocAsync
2024-10-26 16:20:42,286 - root - INFO - Using pytorch cross attention
2024-10-26 16:20:43,470 - root - INFO - [Prompt Server] web root: C:\AI\ComfyUI_windows_portable\ComfyUI\web
2024-10-26 16:20:45,456 - root - INFO - 
Import times for custom nodes:
2024-10-26 16:20:45,456 - root - INFO -    0.0 seconds: C:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\websocket_image_save.py
2024-10-26 16:20:45,457 - root - INFO -    0.0 seconds: C:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfy-image-saver
2024-10-26 16:20:45,457 - root - INFO -    0.0 seconds: C:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Frame-Interpolation
2024-10-26 16:20:45,457 - root - INFO -    0.0 seconds: C:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-VideoHelperSuite
2024-10-26 16:20:45,457 - root - INFO -    0.0 seconds: C:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-GGUF
2024-10-26 16:20:45,457 - root - INFO -    0.0 seconds: C:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\rgthree-comfy
2024-10-26 16:20:45,457 - root - INFO -    0.0 seconds: C:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_Comfyroll_CustomNodes
2024-10-26 16:20:45,457 - root - INFO -    0.1 seconds: C:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-tooling-nodes
2024-10-26 16:20:45,457 - root - INFO -    0.3 seconds: C:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager
2024-10-26 16:20:45,457 - root - INFO -    0.4 seconds: C:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack
2024-10-26 16:20:45,457 - root - INFO -    0.6 seconds: C:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-DeepFuze
2024-10-26 16:20:45,457 - root - INFO - 
2024-10-26 16:20:45,466 - root - INFO - Starting server

2024-10-26 16:20:45,466 - root - INFO - To see the GUI go to: http://127.0.0.1:8188
2024-10-26 16:20:49,493 - root - INFO - got prompt
2024-10-26 16:20:53,490 - root - ERROR - !!! Exception during processing !!! C:\AI\ComfyUI_windows_portable\ComfyUI\output\deepfuze\faceswap_17299488522335312.mp4 could not be loaded with cv.
2024-10-26 16:20:53,492 - root - ERROR - Traceback (most recent call last):
  File "C:\AI\ComfyUI_windows_portable\ComfyUI\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\AI\ComfyUI_windows_portable\ComfyUI\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\AI\ComfyUI_windows_portable\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "C:\AI\ComfyUI_windows_portable\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-DeepFuze\nodes.py", line 928, in faceswampgenerate
    return load_video_cv(faceswap_filename,0,'Disabled',512,512,0,0,1)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-DeepFuze\nodes.py", line 446, in load_video_cv
    (width, height, fps, duration, total_frames, target_frame_time) = next(gen)
                                                                      ^^^^^^^^^
  File "C:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-DeepFuze\nodes.py", line 365, in cv_frame_generator
    raise ValueError(f"{video} could not be loaded with cv.")
ValueError: C:\AI\ComfyUI_windows_portable\ComfyUI\output\deepfuze\faceswap_17299488522335312.mp4 could not be loaded with cv.

2024-10-26 16:20:53,493 - root - INFO - Prompt executed in 3.93 seconds
2024-10-26 16:22:11,515 - root - INFO - got prompt
2024-10-26 16:22:14,745 - root - ERROR - !!! Exception during processing !!! C:\AI\ComfyUI_windows_portable\ComfyUI\output\deepfuze\faceswap_17299489334242578.mp4 could not be loaded with cv.
2024-10-26 16:22:14,746 - root - ERROR - Traceback (most recent call last):
  File "C:\AI\ComfyUI_windows_portable\ComfyUI\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\AI\ComfyUI_windows_portable\ComfyUI\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\AI\ComfyUI_windows_portable\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "C:\AI\ComfyUI_windows_portable\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-DeepFuze\nodes.py", line 928, in faceswampgenerate
    return load_video_cv(faceswap_filename,0,'Disabled',512,512,0,0,1)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-DeepFuze\nodes.py", line 446, in load_video_cv
    (width, height, fps, duration, total_frames, target_frame_time) = next(gen)
                                                                      ^^^^^^^^^
  File "C:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-DeepFuze\nodes.py", line 365, in cv_frame_generator
    raise ValueError(f"{video} could not be loaded with cv.")
ValueError: C:\AI\ComfyUI_windows_portable\ComfyUI\output\deepfuze\faceswap_17299489334242578.mp4 could not be loaded with cv.

2024-10-26 16:22:14,748 - root - INFO - Prompt executed in 3.16 seconds
2024-10-26 16:33:13,190 - root - INFO - got prompt
2024-10-26 16:33:16,454 - root - ERROR - !!! Exception during processing !!! C:\AI\ComfyUI_windows_portable\ComfyUI\output\deepfuze\faceswap_1729949595164198.mp4 could not be loaded with cv.
2024-10-26 16:33:16,455 - root - ERROR - Traceback (most recent call last):
  File "C:\AI\ComfyUI_windows_portable\ComfyUI\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\AI\ComfyUI_windows_portable\ComfyUI\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\AI\ComfyUI_windows_portable\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "C:\AI\ComfyUI_windows_portable\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-DeepFuze\nodes.py", line 928, in faceswampgenerate
    return load_video_cv(faceswap_filename,0,'Disabled',512,512,0,0,1)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-DeepFuze\nodes.py", line 446, in load_video_cv
    (width, height, fps, duration, total_frames, target_frame_time) = next(gen)
                                                                      ^^^^^^^^^
  File "C:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-DeepFuze\nodes.py", line 365, in cv_frame_generator
    raise ValueError(f"{video} could not be loaded with cv.")
ValueError: C:\AI\ComfyUI_windows_portable\ComfyUI\output\deepfuze\faceswap_1729949595164198.mp4 could not be loaded with cv.

2024-10-26 16:33:16,456 - root - INFO - Prompt executed in 3.19 seconds
2024-10-26 16:40:58,224 - root - INFO - got prompt
2024-10-26 16:41:01,397 - root - ERROR - !!! Exception during processing !!! C:\AI\ComfyUI_windows_portable\ComfyUI\output\deepfuze\faceswap_17299500601466925.mp4 could not be loaded with cv.
2024-10-26 16:41:01,398 - root - ERROR - Traceback (most recent call last):
  File "C:\AI\ComfyUI_windows_portable\ComfyUI\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\AI\ComfyUI_windows_portable\ComfyUI\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\AI\ComfyUI_windows_portable\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "C:\AI\ComfyUI_windows_portable\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-DeepFuze\nodes.py", line 928, in faceswampgenerate
    return load_video_cv(faceswap_filename,0,'Disabled',512,512,0,0,1)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-DeepFuze\nodes.py", line 446, in load_video_cv
    (width, height, fps, duration, total_frames, target_frame_time) = next(gen)
                                                                      ^^^^^^^^^
  File "C:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-DeepFuze\nodes.py", line 365, in cv_frame_generator
    raise ValueError(f"{video} could not be loaded with cv.")
ValueError: C:\AI\ComfyUI_windows_portable\ComfyUI\output\deepfuze\faceswap_17299500601466925.mp4 could not be loaded with cv.

2024-10-26 16:41:01,400 - root - INFO - Prompt executed in 3.10 seconds
```
## Attached Workflow
Please make sure that workflow does not contain any sensitive information such as API keys or passwords.
```
{"last_node_id":21,"last_link_id":23,"nodes":[{"id":18,"type":"VHS_VideoCombine","pos":{"0":1256,"1":391},"size":{"0":315,"1":310},"flags":{},"order":6,"mode":0,"inputs":[{"name":"images","type":"IMAGE","link":18},{"name":"audio","type":"AUDIO","link":null,"shape":7},{"name":"meta_batch","type":"VHS_BatchManager","link":null,"shape":7},{"name":"vae","type":"VAE","link":null,"shape":7}],"outputs":[{"name":"Filenames","type":"VHS_FILENAMES","links":null,"shape":3}],"properties":{"Node name for S&R":"VHS_VideoCombine"},"widgets_values":{"frame_rate":24,"loop_count":0,"filename_prefix":"AnimateDiff","format":"video/h264-mp4","pix_fmt":"yuv420p","crf":19,"save_metadata":true,"pingpong":false,"save_output":true,"videopreview":{"hidden":false,"paused":false,"params":{}}}},{"id":8,"type":"VHS_VideoCombine","pos":{"0":2072,"1":217},"size":{"0":315,"1":310},"flags":{},"order":7,"mode":0,"inputs":[{"name":"images","type":"IMAGE","link":7},{"name":"audio","type":"AUDIO","link":8,"shape":7},{"name":"meta_batch","type":"VHS_BatchManager","link":null,"shape":7},{"name":"vae","type":"VAE","link":null,"shape":7}],"outputs":[{"name":"Filenames","type":"VHS_FILENAMES","links":null,"shape":3}],"properties":{"Node name for S&R":"VHS_VideoCombine"},"widgets_values":{"frame_rate":24,"loop_count":0,"filename_prefix":"AnimateDiff","format":"video/h264-mp4","pix_fmt":"yuv420p","crf":19,"save_metadata":true,"pingpong":false,"save_output":true,"videopreview":{"hidden":false,"paused":false,"params":{}}}},{"id":14,"type":"DeepfuzePreview","pos":{"0":460,"1":-108},"size":{"0":315,"1":342},"flags":{},"order":3,"mode":0,"inputs":[{"name":"images","type":"IMAGE","link":15}],"outputs":[],"properties":{"Node name for S&R":"DeepfuzePreview"},"widgets_values":[0,0,0,0],"color":"#233","bgcolor":"#355"},{"id":17,"type":"FILM VFI","pos":{"0":953,"1":-38},"size":{"0":443.4000244140625,"1":126},"flags":{},"order":5,"mode":0,"inputs":[{"name":"frames","type":"IMAGE","link":17},{"name":"optional_interpolation_states","type":"INTERPOLATION_STATES","link":null,"shape":7}],"outputs":[{"name":"IMAGE","type":"IMAGE","links":[7,23],"slot_index":0,"shape":3}],"properties":{"Node name for S&R":"FILM VFI"},"widgets_values":["film_net_fp32.pt",10,2]},{"id":20,"type":"LoadImage","pos":{"0":-17,"1":110},"size":{"0":315,"1":314},"flags":{},"order":0,"mode":0,"inputs":[],"outputs":[{"name":"IMAGE","type":"IMAGE","links":[22],"shape":3},{"name":"MASK","type":"MASK","links":null,"shape":3}],"properties":{"Node name for S&R":"LoadImage"},"widgets_values":["FLUX_00198_.png","image"]},{"id":3,"type":"VHS_LoadVideo","pos":{"0":84,"1":554},"size":[247.455078125,655.091796875],"flags":{},"order":1,"mode":0,"inputs":[{"name":"meta_batch","type":"VHS_BatchManager","link":null,"shape":7},{"name":"vae","type":"VAE","link":null,"shape":7}],"outputs":[{"name":"IMAGE","type":"IMAGE","links":[21],"slot_index":0,"shape":3},{"name":"frame_count","type":"INT","links":null,"shape":3},{"name":"audio","type":"AUDIO","links":null,"shape":3},{"name":"video_info","type":"VHS_VIDEOINFO","links":null,"shape":3}],"properties":{"Node name for S&R":"VHS_LoadVideo"},"widgets_values":{"video":"Gen-3 Alpha Turbo 1701759276, quick hairstyle chan, FLUX_00170_1png, M 5.mp4","force_rate":0,"force_size":"Disabled","custom_width":512,"custom_height":512,"frame_load_cap":48,"skip_first_frames":0,"select_every_nth":1,"choose video to upload":"image","videopreview":{"hidden":false,"paused":false,"params":{"frame_load_cap":48,"skip_first_frames":0,"force_rate":0,"filename":"Gen-3 Alpha Turbo 1701759276, quick hairstyle chan, FLUX_00170_1png, M 5.mp4","type":"input","format":"video/mp4","select_every_nth":1}}}},{"id":15,"type":"PreviewImage","pos":{"0":852,"1":568},"size":{"0":305.6710510253906,"1":260.34246826171875},"flags":{},"order":4,"mode":0,"inputs":[{"name":"images","type":"IMAGE","link":16}],"outputs":[],"properties":{"Node name for S&R":"PreviewImage"},"widgets_values":[]},{"id":6,"type":"DeepFuzeFaceSwap","pos":{"0":465,"1":298},"size":{"0":317.4000244140625,"1":454},"flags":{},"order":2,"mode":0,"inputs":[{"name":"source_images","type":"IMAGE","link":22,"slot_index":0},{"name":"target_images","type":"IMAGE","link":21},{"name":"audio","type":"AUDIO","link":null,"shape":7},{"name":"meta_batch","type":"VHS_BatchManager","link":null,"shape":7}],"outputs":[{"name":"IMAGE","type":"IMAGE","links":[15,16,17,18],"slot_index":0,"shape":3},{"name":"frame_count","type":"INT","links":null,"shape":3},{"name":"audio","type":"AUDIO","links":[8],"slot_index":2,"shape":3},{"name":"video_info","type":"VHS_VIDEOINFO","links":null,"shape":3}],"properties":{"Node name for S&R":"DeepFuzeFaceSwap"},"widgets_values":["restoreformer_plus_plus","inswapper_128","clear_reality_x4","retinaface",0,0,0,0,0,"cpu",24,0,"deepfuze",false,true],"color":"#233","bgcolor":"#355"},{"id":21,"type":"PreviewImage","pos":{"0":1719,"1":363},"size":{"0":305.6710510253906,"1":260.34246826171875},"flags":{},"order":8,"mode":0,"inputs":[{"name":"images","type":"IMAGE","link":23}],"outputs":[],"properties":{"Node name for S&R":"PreviewImage"},"widgets_values":[]}],"links":[[7,17,0,8,0,"IMAGE"],[8,6,2,8,1,"AUDIO"],[15,6,0,14,0,"IMAGE"],[16,6,0,15,0,"IMAGE"],[17,6,0,17,0,"IMAGE"],[18,6,0,18,0,"IMAGE"],[21,3,0,6,1,"IMAGE"],[22,20,0,6,0,"IMAGE"],[23,17,0,21,0,"IMAGE"]],"groups":[],"config":{},"extra":{"ds":{"scale":1.4641000000000006,"offset":[-1601.748399437035,-195.83346332531016]}},"version":0.4}
```

## Additional Context
(Please add any additional context or steps to reproduce the error here)

**Comment by klaatuka** [comment]
![Снимок экрана 2024-10-26 160105](https://github.com/user-attachments/assets/c8f96188-bdaa-4a3b-9785-b5b2bdb54507)
and I noticed it during the installation

**Comment by IntellectzProductions** [comment]
this very frustrating when you do everything that is supposed to "fix" it and it still doesn't work. Anybody know why this cv error is happening? When I go into comfy output/deepfuze. The file isn't even in there to load.

**Comment by cruelacid** [comment]
I get the same error when using the DeepFuze Lipsync node. The readme mentions this error is related to onnxruntime not being installed, however I can see it is definitely installed with pip install.

**Comment by quantum909** [comment]
This worked for me

https://stackoverflow.com/questions/72356588/could-not-locate-zlibwapi-dll-please-make-sure-it-is-in-your-library-path

**Comment by asutermo** [comment]
This appears to be due to pre_check failing on lip_syncer when downloading 

https://github.com/facefusion/facefusion-assets/releases/download/models/open_nsfw.onnx
